import { useEffect, useState } from "react";
import Head from "next/head";
import Image from "next/image";
// style
import styles from "../styles/Home.module.scss";
// mock
import { data } from "../mock/data.js";
import { groupList } from "../mock/groupList.js";
import { options } from "../mock/dropdownOptions.js";
// components
import CardList from "@/components/cardList";
import Itinerary from "@/components/itinerary";
import DropdownSelect from "@/components/dropdown";
import GroupShow from "@/components/groupShow";
// logo and images
import logoIcon from "../../public/assets/images/logo.svg";
import heroImage from "../../public/assets/images/hero.jpeg";
import bannerImage from "../../public/assets/images/banner.jpeg";

export default function Home() {
  const [inputDropdownValue, setInputDropdownValue] = useState({ label: "Mostra tutti" });
  const [dataFiltered, setDataFiltered] = useState([]);
  const [selectedLeft, setSelectedLeft] = useState("");
  const [selectedRight, setSelectedRight] = useState("");

  useEffect(() => {
    if (inputDropdownValue.label === "Mostra tutti") {
      setDataFiltered(data);
    } else if (
      inputDropdownValue.label !== "Mostra per porto di partenza" &&
      inputDropdownValue.label !== "Seleziona un porto"
    ) {
      setDataFiltered(
        data.filter((item) => item.departure.Port.includes(inputDropdownValue.label))
      );
    }
  }, [inputDropdownValue.value]);

  return (
    <>
      <Head>
        <title>Sea Adventures</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <div className={styles.header__logo}>
          <Image src={logoIcon} width={40} height={40} alt="logo" />
        </div>
      </header>
      <main className={styles.main}>
        <section className={styles.hero}>
          <div className={styles.hero__image}>
            <Image src={heroImage} width={1920} height={1279} alt="hero" />
          </div>
          <h2 className={styles.hero__text}>Lorem ipsum dolor sit amet consectetur.</h2>
        </section>
        <section className={styles.content}>
          <div className={styles.container}>
            <DropdownSelect
              options={groupList}
              handleChange={setInputDropdownValue}
              setOtherSelected={setSelectedRight}
              selected={selectedLeft}
              setSelected={setSelectedLeft}
            />
            <DropdownSelect
              options={options}
              handleChange={setInputDropdownValue}
              setOtherSelected={setSelectedLeft}
              selected={selectedRight}
              setSelected={setSelectedRight}
            />
          </div>
          {inputDropdownValue.label === "Mostra per porto di partenza" ? (
            <GroupShow data={data} />
          ) : (
            <CardList data={dataFiltered} />
          )}
        </section>
        <section className={styles.banner}>
          <div className={styles.banner__image}>
            <Image src={bannerImage} width={1920} height={1279} alt="banner" />
          </div>
          <div className={styles.banner__text}>
            <div className={styles.banner__text__wrapper}>
              <h2 className={styles.banner__firstText}>+20</h2>
              <h2 className={styles.banner__firstText}>Destinazioni</h2>
            </div>
            <div className={styles.banner__text__wrapper}>
              <h2 className={styles.banner__secondText}>+15</h2>
              <h2 className={styles.banner__secondText}>Imbarcazioni</h2>
            </div>
            <div className={styles.banner__text__wrapper}>
              <h2 className={styles.banner__thirdText}>+40</h2>
              <h2 className={styles.banner__thirdText}>Itinerari</h2>
            </div>
          </div>
        </section>
        <section className={styles.itinerary}>
          <Itinerary data={data} />
        </section>
      </main>
    </>
  );
}
